version: '3'

services:
  mysql:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
  app:
    build: . # 相当于 docker build .
    ports:
      - '3000:3000'
    depends_on:
      - mysql